name: build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x

permissions:
  contents: read
  actions: write

jobs:
  main:
    name: Build [PHP ${{ matrix.php-version }}][PHPUnit ${{ matrix.phpunit-version }}]
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        phpunit-version:
          - '^11.5'
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        include:
          - phpunit-version: '^12.5'
            php-version: '8.3'
          - phpunit-version: '^12.5'
            php-version: '8.4'
          - phpunit-version: '^12.5'
            php-version: '8.5'
          - phpunit-version: '^13.0'
            php-version: '8.4'
          - phpunit-version: '^13.0'
            php-version: '8.5'

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup PHP ${{ matrix.php-version}}
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php-version}}
          extensions: xdebug
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_FILES_DIR }}
          key: composer-php_${{ matrix.php-version }}-phpunit_${{ matrix.phpunit-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-php_${{ matrix.php-version }}-phpunit_${{ matrix.phpunit-version }}-
            composer-php_${{ matrix.php-version }}-
            composer-

      - name: Setup Composer's GitHub OAuth access
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer require --ansi "phpunit/phpunit:${{ matrix.phpunit-version }}" --with-all-dependencies
          composer update --ansi
          composer audit --ansi --abandoned=report

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer check --ansi --verbose --diff

      - name: Run PHPStan Static Analysis Check
        run: vendor/bin/phpstan analyse --ansi

      - name: Tests on PHPUnit ${{ matrix.phpunit-version }}
        run: |
          vendor/bin/phpunit --color=always
        env:
          TACHYCARDIA_MONITOR_GA: enabled

      - name: Upload code coverage to Coveralls
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          file: build/logs/clover.xml
          flag-name: PHP ${{ matrix.php-version }} - PHPUnit ${{ matrix.phpunit-version }}
          parallel: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coveralls-finish:
    name: Notify Coveralls API
    needs: main
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}

    steps:
      - name: Upload to Coveralls API
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
