name: release

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_ACTIONS_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Nexus Tachycardia ${{ github.ref_name }}" \
            --draft \
            --generate-notes
